### ISSUE TITLE
No module named `queue` when downloading subtitle

### ISSUE THREAD

**Issue by memborg** [romanvm/service.addic7ed#30]
**Issue description:**

After the search results are back from <http://addic7ed.com> and the one I want is selected for download the download fails.

**Kodi debug log:**

```
ERROR <general>: XFILE::CDirectory::GetDirectory - Error getting plugin://service.subtitles.rvm.addic7ed/?action=search&languages=English&preferredlanguage=Danish
INFO <general>: initializing python engine.
ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
Error Type: <class 'ModuleNotFoundError'>
Error Contents: No module named 'queue'
Traceback (most recent call last):
    File "%APPDATA%\Kodi\addons\service.subtitles.rvm.addic7ed\main.py", line 6, in <module>
    from addic7ed.actions import router
    File "%APPDATA%\Kodi\addons\service.subtitles.rvm.addic7ed\addic7ed\actions.py", line 14, in <module>
    from . import parser
    File "%APPDATA%\Kodi\addons\service.subtitles.rvm.addic7ed\addic7ed\parser.py", line 19, in <module>
    from .webclient import Session
    File "%APPDATA%\Kodi\addons\service.subtitles.rvm.addic7ed\addic7ed\webclient.py", line 4, in <module>
    import requests
    File "%APPDATA%\Kodi\addons\script.module.requests\lib\requests\__init__.py", line 43, in <module>
    import urllib3
    File "%APPDATA%\Kodi\addons\script.module.urllib3\lib\urllib3\__init__.py", line 13, in <module>
    from .connectionpool import HTTPConnectionPool, HTTPSConnectionPool, connection_from_url
    File "%APPDATA%\Kodi\addons\script.module.urllib3\lib\urllib3\connectionpool.py", line 37, in <module>
    from .packages.six.moves import queue
    File "%APPDATA%\Kodi\addons\script.module.urllib3\lib\urllib3\packages\six.py", line 91, in __get__
    result = self._resolve()
    File "%APPDATA%\Kodi\addons\script.module.urllib3\lib\urllib3\packages\six.py", line 113, in _resolve
    return _import_module(self.mod)
    File "%APPDATA%\Kodi\addons\script.module.urllib3\lib\urllib3\packages\six.py", line 82, in _import_module
    __import__(name)
ModuleNotFoundError: No module named 'queue'
-->End of Python script error report<--
                                                   
INFO <general>: Python interpreter stopped
ERROR <general>: XFILE::CDirectory::GetDirectory - Error getting plugin://service.subtitles.rvm.addic7ed/?action=search&languages=English&preferredlanguage=Danish
```

**Additional context**

* Windows 10
* Kodi 19.1 Matrix
* Addicted subtitle 3.17 downloaded from the official Kodi Repos.

**Comment by romanvm** [comment]
Full debug log please.

**Comment by memborg** [comment]
Full log added

[kodi.log](https://github.com/romanvm/service.addic7ed/files/7273472/kodi.log)

**Comment by romanvm** [comment]
The issue is not reproduced on v.19.1 Windows 64-bit build from kodi.tv. Try to re-install Kodi. From what I see this is not a problem with this addon but with the built-in Python in Kodi.

**Comment by memborg** [comment]
Alright. I will it a go

**Comment by memborg** [comment]
A reinstall of Kodi fixes my problem. Thank you for pointing that out.
