### ISSUE TITLE
Error Exception:

### ISSUE THREAD

**Issue by TilipTip** [romanvm/service.addic7ed#6]
Hi,
I can't make this addon work, I've always an error when trying to look for subtitle
( I ve correctly set up my login/password )

Here the log, if u have any clue of what is going wrong, I'll take any advice:

20:50:03.557 T:3455087520  NOTICE: service.subtitles.rvm.addic7ed: Searching for subs...
20:50:05.704 T:3455087520  NOTICE: service.subtitles.rvm.addic7ed: Found subs for "modern family 10x12"
20:50:05.718 T:3455087520   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'NoneType' object has no attribute 'parent'
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/service.subtitles.rvm.addic7ed/main.py", line 9, in <module>
                                                router(sys.argv[2][1:])
                                              File "/storage/.kodi/addons/service.subtitles.rvm.addic7ed/addic7ed/core.py", line 248, in router
                                                search_subs(params)
                                              File "/storage/.kodi/addons/service.subtitles.rvm.addic7ed/addic7ed/core.py", line 234, in search_subs
                                                episode_data.filename)
                                              File "/storage/.kodi/addons/service.subtitles.rvm.addic7ed/addic7ed/core.py", line 64, in display_subs
                                                for item in subs_list:
                                              File "/storage/.kodi/addons/service.subtitles.rvm.addic7ed/addic7ed/parser.py", line 137, in parse_episode
                                                download_tag = download_button.parent.parent
                                            AttributeError: 'NoneType' object has no attribute 'parent'
                                            -->End of Python script error report<--
20:50:05.899 T:3342521248   ERROR: GetDirectory - Error getting plugin://service.subtitles.rvm.addic7ed/?action=search&languages=French&preferredlanguage=French

**Comment by romanvm** [comment]
Please provide full [debug log](https://kodi.wiki/view/Log_file/Advanced) with your issue.

**Comment by TilipTip** [comment]
Here the full log:
[kodi.log](https://github.com/romanvm/service.addic7ed/files/2824187/kodi.log)

**Comment by romanvm** [comment]
Thanks, I'll look into it.
